//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NegociosYContactos.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Business
    {
        public Business()
        {
            this.BusinessProduct = new HashSet<BusinessProduct>();
            this.AspNetUsers = new HashSet<AspNetUsers>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string UrlImage { get; set; }
        public string Style { get; set; }
        public System.DateTime InitDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public bool Premium { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<BusinessProduct> BusinessProduct { get; set; }
        public virtual ICollection<AspNetUsers> AspNetUsers { get; set; }
    }
}
